name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        uses: actions/setup-node@master
        with:
        node-version: 20

      - name: Install SSH client
        run: sudo yum install -y openssh-clients

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} root@13.60.20.23 'cd /root/chat-test-backend && git pull && npm install && npm run start && pm2 restart app'
